### ISSUE TITLE
LilyPond Update to 2.22.0 (January 10th, 2021)

### ISSUE THREAD

**Issue by Joshua-Mastachi** [lhl2617/VSLilyPond-formatter#33]
## LilyPond Update to 2.22.0 (January 10th, 2021)

They just uploaded LilyPond, so I just put this here to ask if this extension is going to be updated. (Ignore the date in the URL)

https://lilypond.org/news.es.html#LilyPond-2_002e21_005e82-released-December-15_002c-2020

**Comment by lhl2617** [comment]
Hi! Thanks for this! The version dependent extension is actually https://github.com/lhl2617/VSLilyPond-snippets--I'll update this tomorrow!

**Comment by lhl2617** [comment]
https://github.com/lhl2617/VSLilyPond-snippets bumped to 0.0.5 supporting 2.22. Thanks for flagging this :D
